version: "3"

services:
    db:
        image: postgres:latest
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=test_db

    backend:
        container_name: FastAPI
        build: ./server
        image: backend:test
        stdin_open: true
        tty: true
        working_dir: /app/server
        command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8080 --reload"
        volumes:
            - .:/app
            - ./dummy:/var/lib/pgadmin/storage/pgadmin4_pgadmin.org
        ports:
            - "8080:8080"
        depends_on:
            - db

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        ports:
            - "5050:80"
        depends_on:
            - db
