version: "3"

services:
    frontend:
        container_name: Streamlit
        build: client/
        image: frontend:beta
        env_file:
            - client/.env.prod
        working_dir: /app
        ports:
            - "80:8501"
        networks:
            - frontend
        depends_on:
            - backend

    backend:
        container_name: FastAPI
        build: server/
        image: backend:beta
        env_file:
            - server/.env.prod
        working_dir: /app
        command: bash /app/start-reload.sh
        ports:
            - "8080:8080"
        networks:
            - frontend
            - backend
        depends_on:
            - db

    pgadmin:
        container_name: pgAdmin
        image: dpage/pgadmin4
        tty: true
        environment:
            - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
            - PGADMIN_DEFAULT_PASSWORD=admin
        volumes:
            - pgadmin:/var/lib/pgadmin4/storage
        ports:
            - "5050:80"
        networks:
            - backend
        depends_on:
            - db

    db:
        container_name: PostgreSQL
        image: postgres:latest
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
        volumes:
            - pgdata:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - backend

volumes:
    pgadmin:
    pgdata:

networks:
    frontend:
        name: frontend
        driver: bridge
    backend:
        name: backend
        driver: bridge
