"""First migration

Revision ID: 69967722fd33
Revises: 
Create Date: 2021-06-10 06:00:18.364505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69967722fd33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_index(op.f('ix_categories_uid'), 'categories', ['uid'], unique=False)
    op.create_table('customers',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=True)
    op.create_index(op.f('ix_customers_uid'), 'customers', ['uid'], unique=False)
    op.create_table('shops',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_shops_name'), 'shops', ['name'], unique=True)
    op.create_index(op.f('ix_shops_uid'), 'shops', ['uid'], unique=False)
    op.create_table('users',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=100), nullable=False),
    sa.Column('salt', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_uid'), 'users', ['uid'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('importations',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('shop_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['shop_uid'], ['shops.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_importations_date'), 'importations', ['date'], unique=False)
    op.create_index(op.f('ix_importations_uid'), 'importations', ['uid'], unique=False)
    op.create_table('items',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('category_uid', sa.Integer(), nullable=True),
    sa.Column('shop_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_uid'], ['categories.uid'], ),
    sa.ForeignKeyConstraint(['shop_uid'], ['shops.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=True)
    op.create_index(op.f('ix_items_uid'), 'items', ['uid'], unique=False)
    op.create_table('transactions',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('customer_uid', sa.Integer(), nullable=True),
    sa.Column('shop_uid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_uid'], ['customers.uid'], ),
    sa.ForeignKeyConstraint(['shop_uid'], ['shops.uid'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_transactions_date'), 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_uid'), 'transactions', ['uid'], unique=False)
    op.create_table('importation_details',
    sa.Column('importation_uid', sa.Integer(), nullable=False),
    sa.Column('item_uid', sa.Integer(), nullable=False),
    sa.Column('item_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['importation_uid'], ['importations.uid'], ),
    sa.ForeignKeyConstraint(['item_uid'], ['items.uid'], ),
    sa.PrimaryKeyConstraint('importation_uid', 'item_uid')
    )
    op.create_table('transaction_details',
    sa.Column('transaction_uid', sa.Integer(), nullable=False),
    sa.Column('item_uid', sa.Integer(), nullable=False),
    sa.Column('item_price', sa.Float(), nullable=False),
    sa.Column('item_amount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['item_uid'], ['items.uid'], ),
    sa.ForeignKeyConstraint(['transaction_uid'], ['transactions.uid'], ),
    sa.PrimaryKeyConstraint('transaction_uid', 'item_uid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_details')
    op.drop_table('importation_details')
    op.drop_index(op.f('ix_transactions_uid'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_date'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_items_uid'), table_name='items')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_table('items')
    op.drop_index(op.f('ix_importations_uid'), table_name='importations')
    op.drop_index(op.f('ix_importations_date'), table_name='importations')
    op.drop_table('importations')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_uid'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_shops_uid'), table_name='shops')
    op.drop_index(op.f('ix_shops_name'), table_name='shops')
    op.drop_table('shops')
    op.drop_index(op.f('ix_customers_uid'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_categories_uid'), table_name='categories')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
