"""Second migration

Revision ID: be41e9010db7
Revises: 69967722fd33
Create Date: 2021-06-10 07:08:45.199661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be41e9010db7'
down_revision = '69967722fd33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_customers_name', table_name='customers')
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.create_index('ix_customers_name', 'customers', ['name'], unique=False)
    # ### end Alembic commands ###
